---
- name: Instalar y configurar NFS
  hosts: nfs
  become: yes
  tasks:

    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar nfs-kernel-server (incluye rpcbind)
      apt:
        name: nfs-kernel-server
        state: present

    - name: Habilitar y arrancar nfs-kernel-server
      systemd:
        name: nfs-kernel-server
        enabled: yes
        state: started

    - name: Habilitar y arrancar rpcbind
      systemd:
        name: rpcbind
        enabled: yes
        state: started

    - name: Crear el directorio compartido
      file:
        path: /var/nfsshare
        state: directory
        mode: '0755'

    - name: Configurar exportaciones NFS
      copy:
        dest: /etc/exports
        content: |
          /var/nfsshare 192.168.100.0/24(rw,sync,no_subtree_check)
        owner: root
        group: root
        mode: '0644'

    - name: Recargar exportaciones NFS
      command: exportfs -ra

    - name: Add Helm repo for nfs-subdir-external-provisioner
      ansible.builtin.shell: |
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      args:
        warn: false

    - name: Update Helm repositories
      ansible.builtin.shell: helm repo update
      args:
        warn: false

    - name: Install nfs-subdir-external-provisioner via Helm
      ansible.builtin.shell: >
        helm install nfs-provisioner
        nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        --set nfs.server=192.168.100.199
        --set nfs.path=/var/nfsshare
        --set storageClass.name=nfs-provisioner
      args:
        warn: false

    - name: Patch the storage class to make it default
      ansible.builtin.shell: >
        oc patch storageclass nfs-provisioner
        -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      args:
        warn: false
